#!/bin/bash
# Manual deployment helper for Render
# Since API has strict requirements, use this one-liner or dashboard

echo "🚀 Bhasha Kahani - Render Deployment Helper"
echo "=============================================="
echo ""
echo "Since the Render API requires strict formatting,"
echo "here are 2 easy ways to deploy:"
echo ""
echo "METHOD 1: Dashboard (Easiest - 2 minutes)"
echo "-------------------------------------------"
echo "1. Go to: https://dashboard.render.com/services"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect: github.com/Ashwinhegde19/bhasha-kahani"
echo "4. Configure:"
echo "   - Name: bhasha-kahani-api"
echo "   - Branch: feature/backend-sprint"
echo "   - Root Dir: apps/api"
echo "   - Runtime: Python 3"
echo "   - Build: pip install -r requirements.txt"
echo "   - Start: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "   - Plan: Free"
echo "   - Region: Singapore"
echo "5. Add Environment Variables:"
echo "   DATABASE_URL=your_supabase_url"
echo "   SUPABASE_SERVICE_KEY=your_key"
echo "   SARVAM_API_KEY=your_key"
echo "   SECRET_KEY=random_string"
echo "6. Click 'Create Web Service'"
echo ""
echo "METHOD 2: Blueprint (Automatic)"
echo "--------------------------------"
echo "The render.yaml file is already in apps/api/"
echo "Render will auto-read it when you connect the repo!"
echo ""
echo "Your API will be live at:"
echo "https://bhasha-kahani-api.onrender.com"
echo ""
